spring.application.name=smart-ticket-router

# OpenAI
openai.api.key=${OPENAI_API_KEY}
openai.model=gpt-4o-mini

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/smart_ticket_router
spring.datasource.username=suhani.mittal
spring.datasource.password=

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true